### ISSUE TITLE
unexpected end of JSON input

### ISSUE THREAD

**Issue by repercussion** [Wellenline/auddly-server#17]
Fresh install. Docker compose. Android app returns "unexpected end of JSON input". 

```
version: "3"
services:
  app:
    container_name: waveline-api
    restart: always
    build: ./
    environment:
      - MONGO_URL=mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@mongodb/waveline?authSource=admin
      - MUSIC_PATH=/music
      - ART_PATH=/art
      - SPOTIFY_ID=${SPOTIFY_ID}
      - SPOTIFY_SECRET=${SPOTIFY_SECRET}
      - AUTH_ENABLED=true
      - API_KEY=${API_KEY}
      - PORT=5000
      - HOST=https://waveline.${DOMAINNAME}:5000
    volumes:
      - ${MUSIC_PATH}:/music
      - ./.cache:/art
    ports:
      - "5000:5000"
    links:
      - mongodb
    depends_on:
      - mongodb
  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    environment:
      - MONGO_DATA_DIR=/data
      - MONGO_LOG_DIR=/dev/null
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    volumes:
      - ./data/mongo:/data
    ports:
      - 27018:27017
    command: mongod --auth --logpath=/dev/null
```

Android version is stock Q running version 1.5.4 of the app.
